apiVersion: v1
kind: Service
metadata:
  name: javaapp-service
spec:
  type: NodePort   # Change to LoadBalancer if using cloud
  selector:
    app: javaapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007
